---
- name: install ssh guard
  apt:
    pkg: "sshguard"
    state: present 

- name: update sshguard whitelist
  lineinfile:
    dest: /etc/sshguard/whitelist
    regexp: "^{{ item }}"
    line: "{{ item }}"
    state: present
  with_items:
    - "127.0.0.0/8"
    - "::1/128"
    - "10.0.0.0/24"
