---
grafana_security:
  admin_user: admin
  admin_password: "{{ vault_grafana_password }}"

grafana_auth:
  anonymous:
    org_name: "int.512.ch"
    org_role: Viewer

grafana_datasources:
- name: "Prometheus"
  type: "prometheus"
  access: "proxy"
  url: "http://{{ ansible_host }}:9090"
  isDefault: true
grafana_dashboards: []
