---
- name: install sudo package
  apt:
    name: sudo
    state: present

- name: create user till
  user:
    name: till
    password: '$6$0JpKVy8ECZe/djQ5$4qAUBmwVlthrktDohm1ORsZ085TjOEB1mWjTMVhnpfMq2Kj1DE41bYLrG9NqBy4LJMi9IVIbMmtCyZTL1zGPq1'
    shell: /bin/bash
    groups: sudo

- name: register ssh keys for till
  authorized_key:
    user: till
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/till
